### ISSUE TITLE
Problem with parsing interpretations

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1495]
The following library
```
library Test

logic Propositional

spec A =
  prop p
end

spec B =
  prop q
end

interpretation r : A to B = p |-> q end 
```
leads to an error:
```
Analyzing library Test
logic Propositional
Analyzing spec Test?A
Analyzing spec Test?B
Analyzing view Test?r
/home/till/CASL/Hets-lib/error1.het:13.37-13.39: *** Error:
unknown symbols '[end]'
/home/till/CASL/Hets-lib/error1.het:13.37-13.39: *** Error:
unknown symbols '[end]'
hets: user error (Stopped due to errors)
```
This behaviour has been introduced in 8bebc2761b9df8e81e310c27f83b99626d522d6c. @cmaeder, could you have a look at your commit?

**Comment by cmaeder** [comment]
The reason is that the logic Propositional (and QBF) does not exclude `end` as keyword! 

Undoing https://github.com/spechub/Hets/commit/8bebc2761b9df8e81e310c27f83b99626d522d6c is of no help. This change only allows additional annotations that start with `%`.

QBF, unfortunately, is basically a source copy of Propositional.

I believe, the best fix is to extend `propKeywords` by `Common.Lexer.criticalKeywords`.
