### ISSUE TITLE
Cache responses

### ISSUE THREAD

**Issue by eugenk** [spechub/Hets#1500]
Responses should not only be returned directly via HTTP/REST API, but they should be cached.
1. Generate an identifier for each request.
2. Compute the result of the request.
3. Write the result into a file (or similar) identified by the ID of step 1.
4. Respond with those file contents.

This issue is a dependency of #1481.

**Comment by tillmo** [comment]
In `PGIP.Server` look at function `hetsServer'`. This is the core function of the Hets server. The request is bound to the variable `re`. 
The simplest thing to do is to store a [map](https://hackage.haskell.org/package/containers-0.6.2.1/docs/Data-Map.html) of request-response pairs in an [IORef](https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-IORef.html), and look in this map if the same request has been processed in the past.
In order to store a response, you need to modify the function `respond`. Write a new function that first stores the request-response pair and then calls the old `respond`.
