### ISSUE TITLE
use IRIs uniformly in HETS

### ISSUE THREAD

**Issue by mcodescu** [spechub/Hets#1596]
We currently have IRIs defined in OWL2, in Common.IRI and moreover we have CASL identifiers. This complicates things, e.g. when translating from OWL to CASL or when using Common.IRIs for OWL2. Ideally, there should be just one type of identifiers, that we could create by extending Common.IRI with some mixfix annotations to cover CASL identifiers as well. We should also have a convention, documented in the wiki, about implicit values for fields in the IRI type. As a result, all logics (including CASL and OWL2) should use the new Common.IRI type.

Hets modules to look at: `Common.IRI` (datatype `IRI`), `OWL2.AS`  (datatype `QName`, same as `IRI`, but different from `IRI` in  `Common.IRI`), `Common.Id` (datatype `Id`). These need to be integrated into a uniform datatype. Later on, look at the parsers:  `Common.IRI`, `OWL2.Parse`, `Common.Token` (e.g. `parseId`).

**Comment by tillmo** [comment]
For mapping CASL IDs to IRIs, if there is no empty prefix, we need a default. This could be the IRI of the library and should be consistent with Ontohub. What happens with fully qualified names `f:s->t`, infixes `__+__` and compound IDs `List[Elem]`? First idea: just include them verbatim. Does the IRI syntax allow this?

**Comment by tillmo** [comment]
The problem is that in the standard http://www.ietf.org/rfc/rfc3987.txt brackets `[]` are forbidden in IRIs, while some symbols like `+` and `:` are allowed (at least in the local part). However, all unicode characters beyond ASCII are allowed, too. Hence we could replace square brackets by some unicode brackets. Alternatively, round brackets `()` are allowed, too (but these are already used for application to arguments), as well as curly braces `{}` (but these already are used for DOL structured OMS).

**Comment by tillmo** [comment]
For mapping CASL IDs to IRIs, if there is no empty prefix, we need a default. This could be the IRI of the library and should be consistent with Ontohub. However, in Ontohub, we need to disambiguate between OMS, mappings, symbols, axiom names etc. We could append a keyword `OMS`, `symbol` etc. to the IRI, which is quite unusual, but from a Hets perspective this would work better than prepending it, because Hets needs to work not only with Ontohub, but also with other sources on the web.

**Comment by tillmo** [comment]
Another question is whether we use the IRI of the location of the document or the IRI in the `library` declaration within the document. (This is comparable to: IRI of the location of an OWL document versus IRI declared in the `Ontology` declaration.) It seems that we should use the latter, because this is the explicitly declared - even if this breaks linked data principles in case where the two IRIs differ.

**Comment by BerndKB** [comment]
Since the problem of incomplete character sets seems to occur with several people, we might try
"‚" -  1738 - U+201A single lower-9 quotation mark
that displays well her, in Protégé and in my TextEdit editor.
I have not found a really FAT comma ...

**Comment by BerndKB** [comment]
I encountered another Problem, perhaps only with Protégé (?): if we use the following names
C［XˌY］
D〚X‚Y〛
E〚X❜Y〛
then the full IRI (with the "Show Full IRI" option) will show correctly, but without this option Protégé displays
C［XˌY］
‚Y〛
❜Y〛
i.e. the text before the resp. "comma"  is taken to be part of the URI prefix.
If it stays that way, it will be extremely confusing for the user.

**Comment by tillmo** [comment]
yes, I can confirm this. The problem is the comma. Only ˌ seems to work. So for example F〚XˌY〛works for me.

**Comment by BerndKB** [comment]
Yes, F〚XˌY〛works for me also.

**Comment by clange** [comment]
Some thoughts while I'm reading this. I have bit yet read the comments to the end. @BerndKB BTW good to "see" you here. I was also at ISWC (just the main conference); didn't manage to talk to you there, but I heard some of my colleagues did.

Another alternative character for enclosing type arguments might be `<...>` (think of Java or C++ generics), but this is even less allowed in IRIs than other bracket characters, probably because it's commonly used to enclose complete IRIs.

**Comment by clange** [comment]
The discussion about prepending the entity kind to IRIs reminds me of another possible solution: following the approach of [punning in OWL 2](https://www.w3.org/TR/owl2-new-features/#F12:_Punning), i.e. allowing the use of the same name for different entities having different entity kinds, where the kind of an entity is determined from the syntactic context.

**Comment by clange** [comment]
In any case I would not mess with the mechanism of "prefix expansion by concatenation", which DOL reuses from the specification of CURIEs in RDFa, and which occurs similarly in related standards, including SPARQL and Turtle. The beauty of this mechanism is its simplicity. Or, on the contrary, if we wanted to deviate from this mechanism, we should be bold instead of half-hearted and do away with it completely, i.e. devise a powerful mechanism for abbreviating long identifiers that doesn't have to respect the restrictions of any existing standard (except maybe RFC 3987). As an analogy, compare the URI syntax of MMT, which, IIRC, has its own approach to relative paths, which is not supported by any other implementation but is self-contained and makes a lot of sense for the MMT use cases.

**Comment by clange** [comment]
On whether or not to follow linked data principles, one can also take inspiration from [MMT's approach of deliberately not following them](https://uniformal.github.io/doc/language/uris.html). Not following them might of course cause confusion because DOL intends to be compatible with languages whose best practice is to follow them, and DOL should also be inviting to the users of such languages.

**Comment by clange** [comment]
Done with my comments. No straightforward _solution_ I could offer, but I hope you'll find my input useful at least.

**Comment by tillmo** [comment]
many thanks for your comments. Do you have the impression that we mess with the mechanism of "prefix expansion by concatenation"?
