### ISSUE TITLE
restore doc generation via haddock

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1683]
This has been deleted from the Makefile with the note

```
# Documentation (no haddock stuff, i.e. "docs/index.html", since developer can
# generated it on demand by themselves and other users dont't need it). Other
# papers (doc/*.pdf) are already pre-generated.
```

However, as a developer, it is most convenient to use "make doc" for generating the documentation with haddock. I certainly do not want to type in a long haddock command with many options by hand. Hence, this functionality should be restored.

**Comment by jelmd** [comment]
Did you try `make docs/index.html` ?

We agreed, that per default no haddock stuff should be build and therefore it was explicitly not included as dependency for target `doc`, because most users intentionally call this target. If you want other targets/names specify, plz (in this context, I'm not sure, what is "easy to remember")..

**Comment by jelmd** [comment]
done somewhere in the past: use `make docs`
