### ISSUE TITLE
Switch to semantic versioning

### ISSUE THREAD

**Issue by eugenk** [spechub/Hets#1713]
We should switch to [semantic versioning](http://semver.org/) because Hets is not only used as an application but also like a library (Hets-server). In the latter case, it is especially important to know whether or not there were breaking changes.

I suggest to
* Rename the file `version_nr` to `version` because the current file name is a mix of English and German and calling it `version` suffices.
* Release often: Every time a new feature is finished (may be one pull request, may be several pull requests), we should increment the version number in the final pull request of a feature and create a release tag as soon as it is merged into master.
* Add command line options/change their output for version queries:
  * `--numeric-version` only prints `0.100.0`
  * `--version` prints `The Heterogeneous Tool Set, version 0.100.0`
  * `--extended-version` prints `The Heterogeneous Tool Set, version 0.100.0, revision abcdef` which might be useful for bug reports.

Before I attempt to change the code accordingly I want to ask @jelmd:
Should we keep the `rev.txt` with the time stamp? It is also used to generate the file name in the `archive` target. Do we need the time stamp in the archive name if we switch to semantic versioning? Instead of the time stamp, I would like to put the commit hash in that file for the `--extended-version` call (and rename the file to `git_revision`).

**Comment by jelmd** [comment]
1+ - sem versions are much better than a timestamp in seconds :-)

IIRC, the primary reason for rev.txt is that Driver/Version.hs can be generated automagically and keeps a 1:1 relation to the commit and thus other SW has an "easy way" to "check for features" by just comparing a single number (and I think, you are actually using it this way somewhere in ontohub). 

Anyway, this never made much sense to me, because with SV (sem. vers.) one could easily achieve the same (e.g. N\*major+N\*minor+tiny = no2cmp with e.g. N=100, M=10000 etc.) and even more ... However, wrt. ontohub this kind of "feature checking" is somehow lame anyway, because of var.mk ...

So yes, I would prefer a static and manually maintained Driver/Version.hs, which gets modified, when a new release should be made (which would also make it easier to automate, i.e. trigger new package makes/distribution). If made this way, one does not need to generate rev.txt anymore (reason 2) before creating the source tar ball (otherwise one would need to ship the repo itself to be able to generate it and would need git, yepp).

3rd reason is, because it is already there, I use it in the `archive` make target to get a unique source tar ball naming required by the PPA crap, yepp. Using SV instead should be fine, too (but requires some minor changes to the makefile/build scripts - shouldn't be that hard).

4th reason is, also because it is already there, I used it to determine, whether one builds from repo or exported repo (ppa case). But if no rev.txt is needed this doesn't matter anymore - whether to build the USER_GUIDE could be deduced on its existence alone - is a little bit dirty, but should be ok ;-). If too annoying, one could probably find an PPA env var, which is usually not set in the normal user env ...

So IMHO: we neither need rev.txt nor any other kind of timestamp/hash/etc., just a properly maintained Driver/Version.hs - just reading its history log is sufficient to map version to git commit, but as you already suggested, one could also tag changes to it accordingly, which makes live even easier. (And this way it would even survive a switch to a different VCS SW).

Finally:

If properly SVed, what does a git_rev hardcoded to the source buys you? IMHO _nothing_ but trouble and higher maintenance burdens. I.e. you need to make sure, that this file is _always_ consistent with the  Driver/Version.hs. Also one does not know its commit hash before the stuff is actually committed, which leads a priory to inconsistencies (also one reason, why experienced SW developer do not include the commit hash/number in the $Id$ line and doc tags of the source files anymore).  Anyway, all this is redundant, because the VCS alias git here already maintains/provides this info. The rev.txt problem/pain is back, beside of its content and possibly name, nothing changed (außer Spesen nix gewesen).  Finally, if the repo switches to a different software, a hard coded "previous_vcs_rev_version_no|hash" is totally useless.

Thus I agree with many experienced software developers/companies: Including VCS native versions/timestamps/hashes into product version or even use it for identification purposes is one of the biggest faults one can make in SW development. Don't do that!

If you want to give verbose version info, it is much more interesting, which compile time flags and which ghc version have been used, on which machine it happend, maybe the user[id], full lsb/OS release, and date/time.

**Comment by eugenk** [comment]
Ok, so no more git revision, and very frequent releases instead. Hence, no `--extended-version`.

**Comment by eugenk** [comment]
And: Instead of maintaining a `version` file, we edit the `Driver/Version.hs` directly. This should simplify the Makefile a little bit more.

**Comment by jelmd** [comment]
Sounds good.

**Comment by jelmd** [comment]
BTW: Should be defined, how many "labels" will be used max. (because it makes life easier and I need at least 2 in add. for proper package versioning). IMHO max = 3 (major.minor.tiny) should be ok.

**Comment by eugenk** [comment]
I would like to go exactly with the specification on http://semver.org: Major.Minor.Patch

Simply put:
> Given a version number MAJOR.MINOR.PATCH, increment the:
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.

**Comment by eugenk** [comment]
... as soon as 1.0.0 is reached.

**Comment by jelmd** [comment]
+1
