### ISSUE TITLE
redesign webgui 

### ISSUE THREAD

**Issue by fabianneuhaus** [spechub/Hets#1801]
I suggest to redesign the existing web gui, because it would enable potential users to test Hets without any barriers. 

here is a suggestion for a design of the page. 
<img width="804" alt="bildschirmfoto 2017-11-27 um 11 05 26" src="https://user-images.githubusercontent.com/2903387/33261586-7b678130-d363-11e7-8fec-bcc49d2bf643.png">

**Comment by eugenk** [comment]
@fabianneuhaus, where can I find the hello world examples for DOL, CASL, OWL, CLIF?

**Comment by tillmo** [comment]
DOL:
```
logic CASL
oms o = sort s
end
```
CASL:
```
spec sp = sort s
end
```
OWL:
```
Ontology: O
Class: A
```
CLIF:
```
(forall (x) (p x))
```

**Comment by eugenk** [comment]
These examples seem to be too small for the "file magic" to detect the file type. Please try them in the (old) web interface to see what syntax errors are thrown.

**Comment by tillmo** [comment]
I needed to correct the first example, because for some reason, Hets does not yet recognize the keyword `oms`. Now it goes through. The second example goes through anyway. The 3rd and 4th examples won't go through without indicating the file type. They go through if you save them in an `.omn`file or `.clif`file, respectively. Note that the file magic should not be used. After all, this is the reason why the user should be able to choose among file types.

**Comment by tillmo** [comment]
Alternatively, you cann also add `logic OWL` or `logic CLIF` to the 3rd and 4th example, resp. However, the user should not be forced to do this. Hets should do this, according to the choice of the user in the dropdown menu.
