### ISSUE TITLE
can't display graphs

### ISSUE THREAD

**Issue by mcodescu** [spechub/Hets#1852]
When trying to run hets on my Ubuntu machine, I get the development graph window but displaying an error: 
![graph](https://user-images.githubusercontent.com/1632930/40546809-81e91b5e-6030-11e8-8e2d-78efd0b61898.png)
After I close this window, at the prompt where hets has been called, a new line appears (last below): 
```
$ hets -g ~/repos/Hets-lib/Basic/Numbers.casl
Analyzing library Basic/Numbers version 1.0
Analyzing spec Basic/Numbers?Nat
Analyzing spec Basic/Numbers?Int
Analyzing spec Basic/Numbers?Rat
Analyzing spec Basic/Numbers?DecimalFraction
hets: Starting daVinci got IO error fd:23: hGetChar: end of file
```
I have recently run an update and the hets package has been updated. When calling the local compilation of hets I get the same behavior. I haven't noticed any update regarding uDrawGraph, and I don't know how to fix this.

**Comment by jelmd** [comment]
Confirmed. It appears, that a missing `$` in the debian rules file caused to not pass `$@` to the script but resolved it immediately to `install` (the make target). So the resulting exec was always `${UDG_HOME}/bin/uDrawGraph "install"` instead of `${UDG_HOME}/bin/uDrawGraph "$@"`.

Next `apt-get update,upgrade [udrawgraph]` should fix it.

**Comment by mcodescu** [comment]
Great, it works now! :+1:
