### ISSUE TITLE
OWL22CASL: remove datatype axioms

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1951]
they should be relegated to a theory that can be optionally imported

**Comment by mcodescu** [comment]
The current implementation checks the current sublogic and adds to the signature obtained by translating from OWL to CASL only the CASL signature needed for the datatypes that are in use. If we don't import it, we will get undefined symbols, so I think this is necessary. (BTW this is not always giving the expected behavior, I'll make another ticket). But I don't get any datatype axioms. Do you have a minimal example?

**Comment by tillmo** [comment]
you are right, so we can close this one.
