### ISSUE TITLE
In OWL, one cannot use xsd:string together with data property facts

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1972]
The following DOL file 
```
logic OWL

ontology O =
 Class: A
Datatype: xsd:string
DataProperty: p
    Domain: A
    Range: xsd:string
Individual: i Types: A Facts: p "test"
end
```
gives an error
```
unknown Datatype: 'string'
```
This does not happen if I use `string` instead of `xsd:string`.

**Comment by mcodescu** [comment]
I think the range axiom should be possible to write without implicitly introducing the declaration of the datatype `xsd:string`.

**Comment by tillmo** [comment]
Indeed, the datatype needs to be declared before it can be used. This follows the OWL standard.
The only problem is that I need to declare it as `string`, while `xsd:string` does not work. This deviates from the OWL standard.

**Comment by mcodescu** [comment]
Then should we reject this ontology?
```
ontology O =
 Class: A

 DataProperty: p
    Domain: A
    Range: xsd:integer
Individual: i Types: A Facts: p 5
end
```
Right now it goes through but the datatype is not declared. Same happens for `xsd:double`.

**Comment by tillmo** [comment]
you are right, these things (also for string) go through in Protégé. So we should accept them, too.

**Comment by mcodescu** [comment]
Apparently the problem is the type of `"test"`, which is `string`. If we write `"test"^^xsd:string`, the example goes through. If we replace "xsd:string" with "string", the example goes through, but only if we don't remove the explicit declaration of the datatype `string`. Should we change from `Literal "test" (Typed string)` to `Literal "test" (Typed xsd:string)` or should we change the test such that `string` is interpreted as `xsd:string`?

**Comment by tillmo** [comment]
I think we should change from `Literal "test" (Typed string)` to `Literal "test" (Typed xsd:string)`.
