### ISSUE TITLE
correct NeSy printer

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#2071]
When running Hets with `./hets -o th -n Train -v2 nesy1.dol` on
```
%prefix( ontohub: <https://ontohub.org/meta/> )%
logic NeSyPatterns
pattern Train = data ontohub:NeSyPatterns.omn
  Symbol -> Training -> Model;
end
```
I get the following output in `nesy1_Train.th`:
```
%prefix(ontohub: <https://ontohub.org/meta/>)%
logic NeSyPatterns
spec Train =
(Model[__genid2], Symbol[__genid0]);
(Symbol[__genid0], Training[__genid1]);
(Training[__genid1], Model[__genid2])
```
I expect to get the input, or least
```
%prefix( ontohub: <https://ontohub.org/meta/> )%
logic NeSyPatterns
pattern Train = data ontohub:NeSyPatterns.omn
  Symbol -> Training;
  Training -> Model;
end
```
That is, generated ids should be suppressed, and pairs should be printed with ->, not with ( , ).

**Comment by daniilsvc** [comment]
In `NeSyPatterns/Logic_NeSyPatterns.hs` in `instance StaticAnalysis NeSyPatterns` we don't define `convertTheory` which converts theory into Doc. The default implementation of `convertTheory` is `Nothing`. Which is not correct I suppose. Because in that case function `printTheory` in `Logic/Logic.hs` fail to pattern match successfully:
```haskell
case (convertTheory lid, basicSpecPrinter sm lid) of
  (Just c, Just p) -> p (c th)  -- what we want
  _ -> print_sign lid s $++$ vsep (map (print_named lid) l)  -- what we actually get
```
Because `convertTheory` is not defined for NeSyPatterns the result of this pattern match is always `(Nothing, Just p)`. And in that case my printer is simply printing signature of NeSyPatterns - this is directly function `printSign` defined in `NeSyPatterns/Sign.hs`. 
I would say we need to implement `convertTheory` for  NeSyPatterns first and then test printer/parser. Otherwise `printTheory` works incorrectly.

**Comment by mcodescu** [comment]
This is not a problem, `convertTheory` is implemented only for OWL and the theories of all other logics are still displayed correctly by printing first the signature and then each of the sentences. The type of NeSyPatterns sentences is the unit. So displaying the theory would only amount to displaying the signature, with a call to `printSign`. This needs to be corrected (e.g. print `X -> Y` instead of `(X, Y)`, don't print the `idMap` because is redundant).
