### ISSUE TITLE
cannot install vampire on focal

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#2098]
The problem I get is:
```
Entpacken von z3-lib-48 (4.8.9-5.20.4) ...
dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/z3-lib-48_4.8.9-5.20.4_amd64.deb (--unpack):
 Versuch, »/usr/lib/x86_64-linux-gnu/libz3.so« zu überschreiben, welches auch in Paket libz3-dev:amd64 4.8.7-4build1 ist
```
So it seems that z3-lib-48 (a dependency of vampire) and libz3-dev have a conflict, which however is not recorded in the package metadata.
Now I have libz3-dev installed because it is a dependency of llvm-10-dev, and that of postgresql-server-dev-12.
Could we possibly get rid of z3-lib-48, which is in the Hets ppa, and replace it with libz3-dev and possibly also libz3-4, which are in Ubuntu universe?

**Comment by jelmd** [comment]
Pkg fixed. After an `apt-get update && apt-get upgrade` it should work.

FWIW: Since the Ubuntu z3 packages are incomplete (no cmake support - required by vampire, no api docs, z3 itself is not even packaged) packages are kept as is, but z3-lib-48:/usr/lib/x86_64-linux-gnu/libz3.so moved to z3-dev-48 package:/usr/lib/x86_64-linux-gnu/z3/libz3.so so that all packages (Ubuntu's and ours) can coexist.

**Comment by tillmo** [comment]
works, many thanks!
