### ISSUE TITLE
problems installing Hets

### ISSUE THREAD

**Issue by mcodescu** [spechub/Hets#2120]
On a fresh installation of Ubuntu 20.04, I have followed the instructions at [hets.eu](hets.eu).
There are problems with uDrawGraph, so I can't run the GUI:
```
sudo apt install hets-desktop
[sudo] password for mcodescu: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hets-desktop : Depends: udrawgraph:i386 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
I already ran `sudo dpkg --add-architecture i386`.

Also, when compiling the Hets sources, I get repeatedly 
```
Cabal file warning in/home/mcodescu/repos/Hets/Hets.cabal@90:22: version operators used. To use version operators the package needs to specify at least 'cabal-version: >= 1.8'.
```
The problem goes away if I change the cabal version as instructed.

**Comment by jelmd** [comment]
The root cause is, that launchpad (LP) does not accept any i386 source packages anymore.

One can outsmart LP by sending an amd64 "envelope" and actually build a i386 package, however, when it starts to publish the successfully built packages, LP smells, that something is not ok.

So now the udrawgraph package on LP is amd64, but actually encloses 32bit binaries, only. Not clean, but the only way I see to circumvent the LP spoon-feeding.

Last but not least - udrawgraph comes with many tcl/tk 8.4 files. However, focal and jammy come with tcl/tk 8.6, so not sure, whether it still can provide all the desired functionality.

Anyway, if you use  http://pkg.iks.cs.ovgu.de/LNF/linux/ubuntu as your hets repo, it should work.
LP still needs some tweaks, but building all the stuff again and again takes a lot of time because of the pretty ill spoon-feeding and dumb functionality - not green at all  ...

**Comment by mcodescu** [comment]
Thank you, I installed uDrawGraph from the .deb at the link you sent me and now I can run the GUI.
@tillmo should we update the instructions on hets.eu?

**Comment by tillmo** [comment]
I cannot reproduce this error. On a fresh Ubuntu 20.04.5, I ran the following commands (actually a subset of those on `hets.eu`):
```
sudo dpkg --add-architecture i386	
sudo apt-add-repository ppa:hets/hets
sudo apt-get install hets-desktop
```
and then I could call `hets -g`.

**Comment by mcodescu** [comment]
This is strange, with the same commands and same version of Ubuntu I got the error in my initial message. 
With the uDrawGraph I got from the link provided by jelmd I get a window when calling `hets -g` but I can't right click on nodes or edges.

**Comment by mcodescu** [comment]
I have uninstalled udrawgraph and repeated the installation steps again. This time I got udrawgraph from the Hets ppa, but I still can't do anything after the development graph is displayed. The only message I get at the command line is 
`Gtk-Message: 09:13:55.045: Failed to load module "canberra-gtk-module"`

**Comment by mcodescu** [comment]
I do get the theory of a node, just extremely slow for a very basic theory. I will close this issue.
